### ISSUE TITLE
Jquery / Migrate not display on my theme.

### ISSUE THREAD

**Issue by onmarketing** [Automattic/_s#1245] opened 2017-12-17 11:36 UTC
Good morning guys,

Hope you're well, looking forward xmas and new year.

I found something last week I download generate theme via https://underscores.me/ there are have  "jquery.js?ver=1.12.4" and "jquery-migrate.min.js?ver=1.4.1" see screenshot below:

![image](https://user-images.githubusercontent.com/29661125/34079072-bb1fe8d4-e31d-11e7-8acd-7c779ec6a622.png)

Last night I download generate theme again https://underscores.me/ there are no "jquery.js?ver=1.12.4" and "jquery-migrate.min.js?ver=1.4.1" see screenshot below:

![image](https://user-images.githubusercontent.com/29661125/34079101-6678fab8-e31e-11e7-94c4-f63bef892615.png)

I don't understand why last night don't have jquery on it. This is what I want in my theme:

<script type='text/javascript' src='http://localhost/../wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
<script type='text/javascript' src='http://localhost/../wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>

I wonder if anyone knows about this.

Thanks,

Shaun.

**Comment by joshmcrty** [comment] 2017-12-18 01:02
This is not a bug; jQuery is not loaded by default in underscores. It must be enqueued by modifying the theme or by a plugin that uses jQuery. Looks like the Visual Composer plugin is enqueueing jQuery in the first screenshot.

**Comment by onmarketing** [comment] 2017-12-18 14:31
Hi,

I deactivate Viusal Composer plugin but still not have "jquery.js?ver=1.12.4" and "jquery-migrate.min.js?ver=1.4.1" on underscores.

Do I need to add wp_enqueue_script in functions.php?

Please advise me what do I need do?

Thanks,

Shaun.

**Comment by grappler** [comment] 2017-12-25 11:52
Hi, 

`_s` does not need jQuery to work. If you are enqueing a script that requires jQuery then you need to add it as a dependancy. https://developer.wordpress.org/themes/basics/including-css-javascript/#scripts

When testing two themes make sure you have all plugins disabled to compare the results.

As this is not an issue with `_s` I will close the issue. You can find support for developing themes on the wp.org forum or WordPress stack exchange.

**Closed by grappler** 2017-12-25 11:52 UTC
