### ISSUE TITLE
Slow Woocommerce shop page

### ISSUE THREAD

**Issue by melt-cdk** [Automattic/_s#1351] opened 2019-03-28 19:43 UTC
Hello,
the woocomerce page (shop homepage) is very slowy than other page like a single product, cart and other. it's only this page, i don't understand why.

Website page : http://praticienshiatsu.melt-cdk.pw/boutique/

I have disable all plugins but it's same.
If i use another theme, nineteen twenty for example, i haven't this problem (same problem with understrap).

tx

**Comment by nielslange** [comment] 2019-05-30 13:29
@melt-cdk At the moment, both http://praticienshiatsu.melt-cdk.pw/boutique/ and http://praticienshiatsu.melt-cdk.pw/ are loading at the same speed, thus, I cannot reproduce the issue that you've reported. However, I see a few fatal errors. It seems that you're still working on your custom theme, thus, I'm going to close this ticket for now.

**Closed by nielslange** 2019-05-30 13:29 UTC
