### ISSUE TITLE
Missing sass compilation scripts and npm packages!

### ISSUE THREAD

**Issue by hasnatbabur** [Automattic/_s#1306] opened 2018-07-13 03:10 UTC
Missing sass compilation scripts and npm packages!

**Comment by Luc45** [comment] 2018-07-23 23:47
I came here for this as well. First of all, thanks for all the effort everyone has put in this amazing theme. It's hard to find a non-opinionated theme to start things on.

But indeed, it would be nice to have files we need to compile SASS if we choose the _sassify version.

**Comment by cinghaman** [comment] 2019-08-06 17:14
Thanks

**Comment by hasnatbabur** [comment] 2019-08-07 22:05
@cinghaman 
Hi, I fall into similar error many times before and a possible solution for you may be running 'npm rebuild node-sass' script after installing packages.

Please have a look here also:
https://stackoverflow.com/questions/46515077/unable-to-install-node-sass-in-my-project?rq=1

Thanks.

**Comment by cinghaman** [comment] 2019-08-07 22:07
Thanks @hasnatbabur I created my own package.json and grunt file all good

**Comment by Ismail-elkorchi** [comment] 2020-03-25 10:51
@hasnatbabur Thank you for reaching out!

I'm going to close this issue since it is a duplicate of https://github.com/Automattic/_s/issues/1149. You may want to subscribe there for updates.

**Closed by Ismail-elkorchi** 2020-03-25 10:51 UTC

**Comment by GoyalAnuj973** [comment] 2020-06-04 08:43
Still not able to resolve the issue!!
