### ISSUE TITLE
Input type search styling

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#895] opened 2016-01-01 10:06 UTC
All the others elements have `box-sizing: border-box;` CSS rule. But in search there is `box-sizing: content-box`:
```
input[type="search"] {
	-webkit-appearance: textfield;
	box-sizing: content-box;
}
```

This creates small styling issues on search field and I personally don't remember to remove the line every time:

```
box-sizing: content-box;
```

My question is that does most of the theme authors remove that line for better styling like I do and default themes do? And should that line be removed from `_s` theme?

**Comment by sixhours** [comment] 2016-01-07 20:52
I'd be in favor of removing this. I'm not sure why it's there, but I've also run into issues styling the search form, particularly in widgets, because it doesn't follow the rest of the site's `border-box` rules.

**Comment by mariomelchor** [comment] 2016-01-08 14:42
+1 I agree as well. I'd be in favor of removing.

**Comment by corvannoorloos** [comment] 2016-01-08 15:06
If I understand correct I'm interested to see what will happen [here](https://github.com/necolas/normalize.css/issues/486) first.

**Comment by sayedwp** [comment] 2016-01-09 05:49
+1. I have also run into the same problem. I should be removed.

**Comment by KickinAss** [comment] 2016-01-15 09:53
Me to, but i think is an error
```
//
// 1. Address `appearance` set to `searchfield` in Safari and Chrome.
// 2. Address `box-sizing` set to `border-box` in Safari and Chrome.
//

input[type="search"] {
  -webkit-appearance: textfield; // 1
  box-sizing: content-box; //2
}
```
1 and 2 do not work as the comment said

**Comment by patrickhlauke** [comment] 2016-01-19 09:58
Dupe of https://github.com/necolas/normalize.css/issues/471 ?

**Comment by corvannoorloos** [comment] 2016-01-19 14:21
> see necolas/normalize.css#471

Thanks for the update!

**Comment by corvannoorloos** [comment] 2016-01-22 00:08
With this merged I'm very much in favor of including the latest normalize.css. @samikeijonen any thoughts?

**Comment by samikeijonen** [comment] 2016-01-22 06:42
Yeah I don't see why not, but I haven't looked does `_s` have custom `normalize.css`. 

But at least `input[type="search"]` :)

**Comment by corvannoorloos** [comment] 2016-01-22 08:02
I haven't compared its current state, but it should only have its comments stripped. https://github.com/Automattic/_s/commit/6c47be98c133c911c1533648225e3b720ba260d4

**Comment by karmatosed** [comment] 2016-02-08 11:24
We have a paired down normalize, so I'd be keen we didn't merge everything in again. We also have Sass to consider. I'm ok with removing the styling though that this ticket originally was looking at.

**Closed** 2016-03-18 21:11 UTC
Labels: Has Patch
