### ISSUE TITLE
rel="designer" in footer link

### ISSUE THREAD

**Issue by samikeijonen** [Automattic/_s#1016] opened 2016-09-02 12:10 UTC
I was wondering why there is `rel="designer"` in footer credit link? It seems that it's invalid html attribute and doesn't have any meaning.

**Comment by mrwweb** [comment] 2016-09-02 16:49
In fact, shouldn't it be `rel="nofollow"`? From [WHATWG](https://blog.whatwg.org/the-road-to-html-5-link-relations#rel-nofollow):

> rel=nofollow "indicates that the link is not endorsed by the original author or publisher of the page, or that the link to the referenced document was included primarily because of a commercial relationship between people affiliated with the two pages."

**Comment by samikeijonen** [comment] 2016-09-02 17:08
Could be, or nothing at all. That would be my best guess. It's just a link.

**Comment by stevengliebe** [comment] 2016-09-02 18:22
It seems Google suggests that if a credit link is used in the footer, it should be nofollow.

https://www.seroundtable.com/google-nofollow-web-design-by-links-19943.html

**Comment by jdevalk** [comment] 2016-09-05 07:06
`nofollow` would make more sense than `designer`, as that's at least an allowed attribute value :) 

But I'd be fine with just removing the `rel=` too.

**Comment by samikeijonen** [comment] 2016-11-26 16:53
Now there is PR #1050 for removing `rel="designer"`.

**Comment by SergeyBiryukov** [comment] 2016-11-27 20:46
> Now there is PR #1050 for removing rel="designer".

Duplicate of #1020?

**Comment by samikeijonen** [comment] 2016-11-28 06:11
Yes, sorry it's duplicate. Let's go with #1020.

**Closed** 2016-12-23 15:05 UTC
