### ISSUE TITLE
Child Theme stylesheet loading issue

### ISSUE THREAD

**Issue by tenman** [Automattic/_s#1075] opened 2017-01-17 01:27 UTC
Hi

```
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );

function theme_enqueue_styles() {
	// load child stylesheet
    wp_enqueue_style( '_s-child-style',
		get_stylesheet_uri(), 
		array('_s-style')
	);
} 
```
```
<link rel='stylesheet' id='_s-style-css'  href='http://example.com/wp/wp-content/themes/_s-child/style.css?ver=4.8-alpha-39909' type='text/css' media='all' />
<link rel='stylesheet' id='_s-child-style-css'  href='http://example.com/wp-content/themes/_s-child/style.css?ver=1484615354' type='text/css' media='all' />

```

`wp_enqueue_style( '_s-style', get_stylesheet_uri() );`

` get_stylesheet_uri()` URL make from get_stylesheet_directory_uri()

**Comment by tyrann0us** [comment] 2017-01-17 07:21
From the [README](https://github.com/Automattic/_s/blob/master/README.md):
> I'm a theme meant for hacking so don't use me as a Parent Theme.

**Comment by tenman** [comment] 2017-01-17 08:28
I feel, _s exists as the mother of default themes

Twentyfourteen - Twentyseventeen themes using get_stylesheet_uri()

I do not know the intention of using this code

**Comment by tenman** [comment] 2017-01-17 08:52
I just wanted to be useful for the _s theme.
Please close it if you think it is not a problem

**Comment by grappler** [comment] 2017-01-17 09:41
Related discussion https://github.com/Automattic/_s/pull/638

**Comment by tenman** [comment] 2017-01-17 11:41
@grappler 

Thank you.

If my point is true
It is only a programming bug. Because get_stylesheet_uri() do not load CSS of parent theme,

**Comment by philiparthurmoore** [comment] 2017-09-10 11:14
@grappler Is this still an issue?

**Comment by joyously** [comment] 2017-09-13 00:09
I think it should be done like this:
```
wp_enqueue_style( '_s-style', get_template_directory_uri() . '/style.css', 
  array(), 
  filemtime(get_template_directory() . '/style.css') );
if ( is_child_theme() ) {
  wp_enqueue_style( get_stylesheet() .'-style', get_stylesheet_uri(),
    array( '_s-style' ), 
    filemtime(get_stylesheet_directory() . '/style.css') );
}

```

**Comment by jrfnl** [comment] 2017-09-13 00:25
I'd advise against using a `filemtime()` call as any file system calls are relatively slow and expensive and this can just as easily be solved with a version number constant.

**Comment by grappler** [comment] 2017-09-13 08:30
@philiparthurmoore I would like to re-discuss automatically loading both the parent and child style.css using PHP as it has been nearly three years since my PR was reverted.

**Comment by joyously** [comment] 2017-09-13 15:01
OK, no file times. How about this?
```
$theme = wp_get_theme();
$version = $theme->parent() ? $theme->parent()->get( 'Version' ) : $theme->get( 'Version' );
wp_enqueue_style( '_s-style', get_template_directory_uri() . '/style.css', 
  array(), 
  $version );
if ( is_child_theme() ) {
  wp_enqueue_style( get_stylesheet() .'-style', get_stylesheet_uri(),
    array( '_s-style' ),
    $theme->get( 'Version' ) );
}

```

**Comment by davidakennedy** [comment] 2017-10-29 19:52
So let's say this issue is about making child theming easier in _s. And let's say we reopen discussion on #638, which was a PR from @grappler that loaded both the parent and child `style.css` files in _s.

I'm torn on this. On one hand, I see the value in making it easier for people creating child themes to not have to worry about loading the parent theme's stylesheet. That makes things easier for the beginning themer experimenting with child themes, as well as those hesitant to touch PHP files at all.

That said, this seems to be more about making child theming easier overall, in all themes, not just _s or themes made with _s. Wouldn't that be a better thing to do? It seems like the ticket opened by @grappler (30797)[https://core.trac.wordpress.org/ticket/30797] just lost steam. I'd advocate for pursuing changes there in Core instead of just _s. Because:

- it benefits all themes.
- reduces confusion about `get_stylesheet_uri()`.
- makes child theming easier.

Why would doing something like the proposed solution in #638 be better in themes as opposed to coming from Core?

I'm leaning toward closing this, but happy to hear from others.

**Comment by joyously** [comment] 2017-10-29 22:24
As you said, the Core ticket has stalled. So changes can be made in _s until such time as the problem is fixed in Core.

I hadn't ever seen the Core ticket before today. It seems that the ticket is written to propose a solution instead of just stating the problem, so all the focus is on that solution. I think the proposed solution does not address the entire problem, which I see as the consequence of a theme following "best practice" of using `get_stylesheet_uri()`, causing the wrong version and handle to be associated with the stylesheet in the case of a child theme. Whether this is a TRT requirement or not (I've never seen it in the requirements document), the theme should be handling its own stylesheet, and perhaps the child's. The child should not be handling the parent's stylesheet, except to dequeue it if desired, because the parent could change how it works at any time. With that problem definition, I think any new function in Core should just enqueue both, like I posted previously, with proper naming (theme prefixes) and versions and dependencies.

**Comment by davidakennedy** [comment] 2018-02-27 20:28
I wanted to double back to this one. After some time, there isn't a lot more interest from the community here. I still think it's a good thing to come from Core, and that as it stands now, _s is friendly enough to child themes.

This can always be revisited later. Thanks for the discussion, everyone!

**Closed by davidakennedy** 2018-02-27 20:28 UTC
Labels: Suggest Close
