### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in …/wp-includes/post-template.php on line 310

### ISSUE THREAD

**Issue by tomektomczuk** [Automattic/_s#1371] opened 2019-08-27 12:42 UTC
To fix that you have to: 

downgrade PHP version to 7.1 or edit wp-config.php and replace

define('WP_DEBUG', false);

to

ini_set('display_errors','Off');
ini_set('error_reporting', E_ALL );
define('WP_DEBUG', false);
define('WP_DEBUG_DISPLAY', false);

**Comment by jbotte** [comment] 2019-10-22 03:17
is there a fix for this yet?

**Comment by Ismail-elkorchi** [comment] 2020-03-28 13:59
@tomektomczuk I just tried `_s` on a fresh install of WordPress with PHP 7.4 and I cannot reproduce the issue you are reporting.

Closing for now. Feel free to reopen the issue if you have additional information.

**Closed by Ismail-elkorchi** 2020-03-28 13:59 UTC
