### ISSUE TITLE
No closing php tags?

### ISSUE THREAD

**Issue by rainman20** [Automattic/_s#996] opened 2016-07-30 23:50 UTC
Is there any reason the php tag is not closed in `page.php` and `single.php` and a few other places?

```
<?php
get_sidebar();
get_footer();
// why not just close the tag here?
```

**Comment by jrfnl** [comment] 2016-07-31 00:35
It's good practice not to have a php close tag if it would be the last thing in a file. The reason for this best practice is to avoid 'cannot send headers, output started at....' type of errors which are often caused by whitespace after a php close tag.

And while you may think this wouldn't be an issue in the case of a template file, this could still cause issues if you use plugins which turn on some form of output buffering (for whatever reason).

**Comment by alaczek** [comment] 2016-08-12 08:40
@jrfnl is right, closing.

**Closed by alaczek** 2016-08-12 08:40 UTC
