### ISSUE TITLE
Underscode is hacked or bug in server update theme

### ISSUE THREAD

**Issue by vulieumang** [Automattic/_s#1359] opened 2019-05-20 08:43 UTC
When I download from https://underscores.me/
active theme and theme show update available
![image](https://user-images.githubusercontent.com/13487753/58008066-c61f9900-7b15-11e9-8797-565470c4a05d.png)
After update some weird file show and have more chinese langue in there, 
![image](https://user-images.githubusercontent.com/13487753/58008183-0b43cb00-7b16-11e9-8f0f-c96f481c427d.png)

I don't know is a bug or hacked?

**Comment by truong-mts** [comment] 2019-05-21 16:33
Maybe there is a theme has the same slug as your theme. Did you check this case?

**Comment by nielslange** [comment] 2019-05-30 13:12
@vulieumang What @truong-mts said. This issue sounds like you're using the same slug as an existing theme on https://wordpress.org/themes/.

**Comment by vulieumang** [comment] 2019-06-04 12:09
Now it do not show update anymore, Maybe something happen there

**Comment by crunnells** [comment] 2019-06-05 01:24
I agree with @truong-mts  and @nielslange, this was most likely caused by switching the theme slug from `_s` to a slug that already exists in the WordPress.org theme showcase. Closing this issue.

**Closed by crunnells** 2019-06-05 01:24 UTC
