### ISSUE TITLE
500 errors with Underscore - line 13 in embed.php?

### ISSUE THREAD

**Issue by t33b33** [Automattic/_s#1254] opened 2018-01-19 06:58 UTC
Hi all,

I'm a content and marketing person, not a dev, so apologies in advance if my request for help isn't detailed enough.

I've inherited a site that's having an issue: 500 errors happening while editing WooCommerce products (especially variations/attributes). Our site is based off Underscore, and we're running latest Woo and WP, and PHP is 5.6.

Our WPEngine host team found this error log multiple times:

**PHP Fatal error: Call to undefined function get_header() in .../wp-includes/theme-compat/embed.php on line 13, referer: .../wp-includes/theme-compat/embed.php**

Does anyone know if there's a way to rectify this? The lines of code are as follows:

get_header( 'embed' );
14
15 if ( have_posts() ) :
16 while ( have_posts() ) : the_post();
17 get_template_part( 'embed', 'content' );
18 endwhile;
19 else :
20 get_template_part( 'embed', '404' );
21 endif;
22
23 get_footer( 'embed' );

I'm out of my depth but the site's dev is long gone. Thanks in advance for any advice.

**Comment by crunnells** [comment] 2018-02-27 00:26
Howdy @t33b33! Thanks for creating this issue. The code and error you referenced aren't part of  Underscores, but part of the oEmbed code in WordPress core. Since you're having issues when _editing_ products in WooCommerce, I'm fairly certain that the issue is not with the theme, but is likely due to a conflict with another plugin. I'd suggest posting in the [community forums](https://wordpress.org/support/forum/how-to-and-troubleshooting/) for help isolating and identifying the problem.

Since this isn't related to Underscores itself, I'll go ahead and close it. Good luck with your theme!

**Closed by crunnells** 2018-02-27 00:26 UTC
Labels: Suggest Close
